###
GET  http://localhost:3000/app/employees

###
POST  http://localhost:3000/app/employees
Content-Type: application/json

{
    "name":"fast",
    "position":"Snr. Developer",
    "office":"Rome",
    "salary":"2000"
}

###
GET http://localhost:3000/app/employees/607f4ba0ff8695390dcac221

###
DELETE HTTP://localhost:3000/app/employees/607f4ba0ff8695390dcac221

###
PUT HTTP://localhost:3000/app/employees/607f1c807eb523297720b42f
Content-Type: application/json

{
"salary":100000    
}
